apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- statefulset.yaml
- pvc.yaml
- rbac.yaml
- vs-authservice-logout.yaml
- vs-authservice-web.yaml

namespace: istio-system

configMapGenerator:
- envs:
  - params.env
  name: oidc-authservice-parameters
secretGenerator:
- envs:
  - secret_params.env
  name: oidc-authservice-client-info

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: authservice
configurations:
- params.yaml
